package com.jimmiemo.recipes;

import com.jimmiemo.recipes.model.Recipe;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This means that this class is a Controller
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private RecipeRepository recipeRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addRecipe (@RequestParam String name
			, @RequestParam String source) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Recipe n = new Recipe();
		n.setName(name);
		n.setSource(source);
		recipeRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Recipe> getAllRecipes() {
		// This returns a JSON or XML with the users
		return recipeRepository.findAll();
	}

	@GetMapping(path="/recipe")
	public @ResponseBody Recipe getOne(@RequestParam int id) {
		return recipeRepository.findById(id).orElse(null);
	}
}
